apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-0af934da89c12f30f
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-066ee9ea45e89ec54
      my-new-stack-PublicSubnet02:
        id: subnet-0f2e681ae71c78a5a 
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0838d4ae4c63dcabf
      my-new-stack-PrivateSubnet02:
        id: subnet-0b19aa1087b3eafe0 

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true